### ISSUE TITLE
Audit MySQL connections

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/datateam-project#1]
Tableau currently points to the following MySQL data sources:

```
bugzilla-reporting-vip.db.scl3.mozilla.com
buildbot-ro-vip.db.scl3.mozilla.com
dw-ro-vip.metrics.scl3.mozilla.com
generic-ro-large-vip.db.scl3.mozilla.com
generic-ro-zeus.db.phx1.mozilla.com
intranet2.db.corp.phx1.mozilla.com
intranet-ro.db.corp.phx1.mozilla.com
metrics1.db.scl3.mozilla.com
monodb.ro.mktns.mktdb.services.phx1.mozilla.com
observium-rw-vip.db.scl3.mozilla.com
pbx1.voip.mtv2.mozilla.com
collusion-db.mofostaging.net
dw-rw-vip.metrics.scl3.mozilla.com
```

We don't yet know which dashboards use these data sources, or whether some are obsolete. We also don't know the relative importance of any of the dashboards that use data from these sources.

We need to
- audit these connections to understand which dashboards rely on data from these connections
- understand the relative importance of those dashboards
- decide whether the lack of access to any of these data sources could block our launch
- determine how we're going to provide access to those existing data sources
- plumb that access where needed

**Comment by mgreensmith** [comment]
Thre's some existing documentation available at https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=72781125

**Comment by harishnair910** [comment]
Data source | Connected Workbook(s) | Owner | Size
-- | -- | -- | --
bugzilla-reporting-vip.db.scl3.mozilla.com | 0 |   | zero
buildbot-ro-vip.db.scl3.mozilla.com | 1 | Benjamin Sullins | 12KB
dw-ro-vip.metrics.scl3.mozilla.com | 0 | Sheeri Cabrai, Josephine Tanumijaya | zero
intranet2.db.corp.phx1.mozilla.com | 0 | Sheere Cabrai | zero
intranet-ro.db.corp.phx1.mozilla.com | 1 | Jacques Uber | Not known
metrics1.db.scl3.mozilla.com |   | Sheere Cabrai | Not known
monodb.ro.mktns.mktdb.services.phx1.mozilla.com | 0 | PagerDuty | zero
observium-rw-vip.db.scl3.mozilla.com | 0 | Sheere Cabrai | zero
pbx1.voip.mtv2.mozilla.com | 0 | PagerDuty | zero
dw-rw-vip.metrics.scl3.mozilla.com | 0 | Sheere Cabrai | zero

**Comment by cvalaas** [comment]
Why does the bugzilla-reporting-vip show 0 connected workbooks? I thought that was what Maryann and the MOC were looking at ... ?

**Comment by cvalaas** [comment]
Capturing slack convo:
cvalaas [2:46 PM]
@Harish Nair I'm pretty sure the inventory database was recently retired (transferred to infoblox, perhaps?) - so I'm guessing this dashboard is no longer used


jd [2:47 PM]
that is correct, and Corey Shields (cshields) is the manager for that team

cvalaas [2:48 PM]
As for buildbot, the dashboard is named "Buildbot-Test" and the extract is dated "Nov 19, 2014" (in Tableau) - so we can probably retire that as well

Harish Nair [2:48 PM]
i would buy that logic as the status monitor tells me there are no actions on the workbook for more that 3 years now
