### ISSUE TITLE
Fix Shraddha Auth0 issue

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/datateam-project#12]
There's an issue where an LDAP group that Shraddha is a member of, is not getting synched to auth0 and so she cannot access the SSO portal.

Need to escalate to EIS.

**Comment by gozer** [comment]
For what its worth, the LDAP group in question is called 'team_dbeng', and for the auth0 syncing, I think @jdow is the right person to hunt down

**Comment by limed** [comment]
She is already in the right group from what I can see just fyi

**Comment by jdow** [comment]
Please have Shraddha go to sso.mozilla.com and Logout and then back in and see if this resolves the issue.

**Comment by gozer** [comment]
She tried that at least once or twice in the past with no results

**Comment by jdow** [comment]
Perhaps logging in with a different browser? The only time Auth0 syncs groups from LDAP is when there is no existing session and the user has to enter in their username/password in the Auth0 login screen, as opposed to auto-login from a cached session.

**Comment by mgreensmith** [comment]
We've tried explicit logout/logins over multiple browsers, with no joy. Could we get Shradda, @jdow and @gozer in a room to dig into this? This blocks our Tableau migration.

**Comment by gdestuynder** [comment]
i had a quick look and i suspect the logout didnt work for some reason.
logging out from the SSO dashboard *should* work

after talking to Shradda, we were able to log her account out and back in, which sync'd the group data correctly (i verified that)

Note, just in case, this is the global logout: https://auth.mozilla.auth0.com/v2/logout?federated (returns "OK" if it worked). This is similar to what the SSO dashboard does, but it's very explicit

**Comment by mgreensmith** [comment]
OK, we confirmed it's resolved. Thanks for the assist, jabba and kang.
