### ISSUE TITLE
Flat file data sources

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/datateam-project#14]
I heard a comment about copying some flat file data sources. If there's work involved here, please describe it.

**Comment by gozer** [comment]
So, in Tableau land, there are various of data-sources, and one of them is a flat-file. You can just upload a CSV file, XLS document, etc and use it as a data-source, simple.

However, for some funny reason, taking a backup of Tableau doesn't include these flat-files, so to proprely move Tableau's state from SCL3 to AWS, I need a backup, but I'll also need a copy of these flat files.

**Comment by mgreensmith** [comment]
How will we solve this when an instance rolls, if the data does not get restored from a backup? What if someone adds a new flat file in the future?

**Comment by mgreensmith** [comment]
Augment the backup and restore processes to include whatever directory these files live in.
