### ISSUE TITLE
snippets-stats endpoint needed in nubis

### ISSUE THREAD

**Issue by cvalaas** [mozilla-itcloud/datateam-project#21]
Long story short:

- We need to move snippets-stats log processing from our MR cluster in scl3 to nubis
- Log volume is low (only 0.1% of actual hits are sent)
- We just need a web frontend that answers with 200 (maybe that's not even necessary, though?) and logs the hits in a standard-ish apache log format (or close to it)
- Data team will write a script to replicate the current log processing MR job

Here is a sample log entry we get now:

`1.2.33.4 snippets-stats.mozilla.org - [19/Jun/2018:19:00:23 +0000] "GET /foo.html?snippet_name=8458&snippet_full_name=MOCO_global_2018_utility_Focus%20for%20Facebook%20June%20V2_activity%20stream_EN_REL&locale=en-US&country=us&metric=impression&campaign=FocusforFacebookJune HTTP/1.1" 200 344 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" "-" "cached" "ssl:SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256, version=TLSv1.2, bits=128" "node:-" node_s:- req_s:0.000000 retries:0 queued:-`

For log processing, we only need the IP, date, request string, and user-agent. The trailing info is not relevant.

* Create an S3 bucket endpoint and enable logging
    * https://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html
    * The requests from snippets-stats are GET, which is supported
    * IP, request string, user agent, etc should all be there
    * simplest and cheapest web frontend?

Additional logging info: 
Amazon S3 uses the following object key format for the log objects it uploads in the target bucket:TargetPrefixYYYY-mm-DD-HH-MM-SS-UniqueString In the key, YYYY, mm, DD, HH, MM, and SS are the digits of the year, month, day, hour, minute, and seconds (respectively) when the log file was delivered. A log file delivered at a specific time can contain records written at any point before that time. There is no way to know whether all log records for a certain time interval have been delivered or not.
--

**Comment by cvalaas** [comment]
@mgreensmith - Can we up priority on this? Vertica migration should still be priority, but if there's space to work on this it would terrific.

**Comment by mgreensmith** [comment]
- Blocker for S3 is HTTPS on a custom domain. Would need to be fronted with Cloudfront.
- Could be Haul with a cronjob that aggregates access logs (apache or varnish) nightly and pushes to an S3 bucket.
