### ISSUE TITLE
Tableau MI integration broken

### ISSUE THREAD

**Issue by spatilmoz** [mozilla-itcloud/datateam-project#22]
Tableau feeds data to https://www.mozdatacollective.com by embedding reports through a plug-in in the above analytics platform

See example here - https://mozilla-stg.metricinsights.com/extreport/index/index/element/151

I tried to create a similar plug-in in the staging environment pointing to tableau nubis stage and it failed due to trusted authentication. Seems like we need to setup the trusted auth

Reference link on how we had set the trusted auth in SCL3 

https://onlinehelp.tableau.com/current/server/en-us/trusted_auth_trustIP.htm

Please use the MozDataCollective staging environment to test the plugin 
https://mozilla-stg.metricinsights.com

**Comment by gozer** [comment]
This setup is entirely too confusing for me ATM. Looking at dataviz.mozilla.org, for instance, I don't see evidence of the trusted authentication mechanism being used.

Instead, MDC seems to generate iframes that link directly to Tableau, leaving it to SSO to ensure users can access the reports. This means that if a user has access to MDC but *not* Tableau, it won't work.

In any case, I've taken care of the configuration/code necessary to have truated authentication working, even though the MDC plugin doesn't appear to be making use of it.

We have a call with folks from MI tomorrow to sort this out.
