### ISSUE TITLE
Vertica IP whitelisting

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/datateam-project#36]
We have a new requirement to provide direct access to Vertica from Tableau desktop users. This requires us to allow IP-whitelisted access to Vertica (or do a client VPN, or site-to-site VPN, but these are burdensome).

Working plan for implementation:
- Expose Vertica to the internet via an NLB.
- Whitelist Mozilla's VPN egress IPs for access. Since all user traffic is routed through the VPN, users can have access to Vertica from anywhere as long as they're on VPN.
- Whitelist the cloud services Hala egress IPs. This deprecates the need for a VPC endpoint (#19) and generally simplifies the configuration.
 - Vertica will need to be configured to enforce TLS and terminate TLS connections with an appropriate cert.

**Comment by cvalaas** [comment]
Per gcox, new (MDC) VPN endpoints are:

63.245.208.132/32
63.245.208.133/32
63.245.210.132/32
63.245.210.133/32

Old (scl3) endpoint is:
63.245.214.169/32

**Comment by gozer** [comment]
Done.
