### ISSUE TITLE
MaxMind GeoIP database needed

### ISSUE THREAD

**Issue by cvalaas** [mozilla-itcloud/datateam-project#41]
Can we have the etl node install the MaxMind GeoIP database (for the snippets-stats script to use to map IPs to Geographies)?

MaxMind provides an executable (which needs to be compiled) to grab the latest database:
https://github.com/maxmind/geoipupdate

That updater should probably be run weekly.

I can provide the UserID, LicenseKey, and ProductIDs(/EditionIDs?) for the config file.

**Comment by gozer** [comment]
@cvalaas Yeah, can you get me these sekret bits so I can hook it all up ?
