### ISSUE TITLE
Bugzilla MOC dashboard is broken

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/datateam-project#7]
Previously: we had a replica of Bugzilla DB in SCL3. Vertica had direct access to this replica.

Bugzilla was moved to AWS, and now Vertica in SCL3 has lost access to the data.

Vertica will shortly be migrated to AWS, but this won't resolve the issue, because the Bugzilla DB will be in a different account and VPC, and there will be no implicit access. The MOC and security team are philosophically opposed to providing cross-account access to the DB or a replica.

Our options,in order of preference:
- Write a script to extract the relevant data from Bugzilla's REST API and import into Vertica periodically. This is the most development-intensive option.
- Have the Bugzilla team extract data periodically and put it in a shared location (S3 bucket), and Data Team can have an ETL job to import data to Vertica. We coudl write the extract script for them. The disadvantage is that Data team is reliant on the Bugzilla team to provide the data in perpetuity.
- Convince them to allow direct connection, open a cross-account tunnel in AWS. This is problematic from a security perspective, and had unknown networking implications.

**Comment by mgreensmith** [comment]
Shraddha will talk to Marianne to understand her priority for regaining access to this data.

**Comment by cvalaas** [comment]
Sooooo....

Turns out MOC uses a different dashboard ("Nagios - MOC Incident Alerts") which perhaps *was* broken, but is fine now.
That data is pushed FROM nagios (MOC-controlled) TO metrics-logger (and also S3 for Nubis), then loaded into Vertica -- so there should be no interruption when we switch to Nubis.

Hooray!

**Comment by mgreensmith** [comment]
I have never been happier to close an issue.
